distributions:
  nixos:
    package_manager: nix
    install_command: nix-env -iA
    update_command: nix-channel --update && nix-env -u
  arch:
    package_manager: pacman
    install_command: pacman -S
    update_command: pacman -Syu

    aur_helper: yay
    aur_install_command: yay -S
    aur_update_command: yay -Syu
  debian:
    package_manager: apt
    install_command: apt-get install
    update_command: apt-get update && apt-get upgrade
