
# ╭───────────────────╮ #
# │ APPLICATION BINDS │ #
# ╰───────────────────╯ #

# Variable for killing Rofi
$rofiKill = pkill -x rofi

# Variable for AppLauncher
$appLauncher = $rofiKill || $sourcePath/rofilaunch.sh d

# Variable for switching AppLauncher styles
$appLauncherStyles = $rofiKill || $sourcePath/rofiselect.sh

# Variable for WebBrowser
$webBrowser = brave --ozone-platform=wayland --password-store=basic

# Variable for CodeEditor
$codeEditor = code --ozone-platform=wayland

# Variable for DiscordClient
$discordClient = discord --ozone-platform=wayland --enable-wayland-ime --no-sandbox

# Variable for FileExplorer
$fileExplorer = dolphin

# Variables for Terminal Emulators
$terminalEmulator = kitty
$terminalEmulatorAlt = foot

# Variables for Applications
$musicPlayer = audacious

# ~ Kill an app ~ #
bindd = $mainMod, Q, Kill the current active window except Steam, exec, $sourcePath/dontkillsteam.sh

# bindd = $mainMod, Q, Kill the current active window, exec, killactive ""

# ╭───────────────╮ #
# │ Apps Launcher │ #
# ╰───────────────╯ #

# Launch desktop applications
bindd = $mainMod, Space, Open the AppLauncher, exec, $appLauncher

# Launch applauncher style switcher
bindd = $mainMod, A, Change the AppLauncher style, exec, $appLauncherStyles

# ╭────────────────╮ #
# │   QUICK APPS   │ #
# ╰────────────────╯ #

# Launch your favourite WebBrowser
bindd = $mainMod, B, Launch the default WebBrowser, exec, $webBrowser

# Launch your favourite CodeEditor
bindd = $mainMod, C, Launch the CodeEditor, exec, $codeEditor

# Launch your favourite DiscordMessengerClient
bindd = $mainMod, D, Launch the DiscordMessengerClient, exec, $discordClient

# Launch your favourite FileExplorer
bindd = $mainMod, E, Launch the FileExplorer, exec, $fileExplorer

# Launch your favourite MusicPlayer
bindd = $mainMod, M, Launch the MusicPlayer, exec, $musicPlayer

# Launch your favourite TerminalEmulator
bindd = $mainMod, RETURN, Launch the TerminalEmulator, exec, $terminalEmulator
