
# ╭─────────────────────────╮ #
# │ AUTO START APPLICATIONS │ #
# ╰─────────────────────────╯ #

exec-once = pw-play ~/.config/hypr/sound-effects/layered-gunshot-5-90886.mp3
exec-once = pw-play ~/.config/hypr/sound-effects/binary-code-interface-sound-effects-sci-fi-computer-ui-sounds-209403.mp3
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = dbus-update-activation-environment --systemd --all # for XDPH
exec-once = [ workspace special silent ] $terminalEmulator # start a $terminalEmulator on start-up in a special workspace
exec-once = udiskie --no-automount --smart-tray # front-end that allows to manage removable media
exec-once = $sourcePath/resetxdgportal.sh # reset XDPH for screenshare
exec-once = $sourcePath/polkitkdeauth.sh # authentication dialogue for GUI apps
exec-once = $sourcePath/batterynotify.sh # battery notification
exec-once = $sourcePath/swwwallpaper.sh # start wallpaper daemon
exec-once = nm-applet --indicator # systray app for Network/Wifi
exec-once = gammastep -O 4500k # night light for hyprland
exec-once = $clipboardImages # clipboard store image data
exec-once = $clipboardTexts # clipboard store text data
exec-once = blueman-applet # systray app for Bluetooth
exec-once = dunst # start notification demon

# exec-once = hyprctl plugins load ~/.local/share/hyprpm/hyprland-plugins/hyprexpo.so
# exec-once = mprisence # discord custom rich presence for mpris
# exec-once = $sourcePath/browser.sh # set browser
# exec-once = premid # discord custom rich presence
# exec-once = $termServer # launch foot server
# exec-once = ags # launch the system bar
# exec-once = hyprpm enable hyprexpo
# exec-once = scrcpy
# exec-once = udiskie --no-automount --smart-tray # front-end that allows to manage removable media
# exec-once = $scrPath/swwwallpaper.sh # start wallpaper daemon
# exec-once = $scrPath/batterynotify.sh # battery notification
# exec-once = hyprpm reload -n # plugins notification
# exec-once = pypr # start pyprland daemon