
# ╭───────────────╮ #
# │ Input Devices │ #
# ╰───────────────╯ #

input {
    
    kb_layout = us
    follow_mouse = 1
    numlock_by_default = true
    
    touchpad {
        
        natural_scroll = yes
        disable_while_typing = true
        
    }
    
    sensitivity = 0
    force_no_accel = 1
    
}
