
# ╔════════════════════════════════════╗ #
# ║ HYPRLAND KEYBINDINGS CONFIGURATION ║ #
# ╚════════════════════════════════════╝ #

# + ~ For Modifier Bindings, eg: $mainMod. Checkout hyprland.conf ~ + #

# ~ Switch workspaces with $mainMod + [0-9] ~ #
bindd = $mainMod, 1, switch to workspace 1, workspace, 1
bindd = $mainMod, 2, switch to workspace 2, workspace, 2
bindd = $mainMod, 3, switch to workspace 3, workspace, 3
bindd = $mainMod, 4, switch to workspace 4, workspace, 4
bindd = $mainMod, 5, switch to workspace 5, workspace, 5
bindd = $mainMod, 6, switch to workspace 6, workspace, 6
bindd = $mainMod, 7, switch to workspace 7, workspace, 7
bindd = $mainMod, 8, switch to workspace 8, workspace, 8
bindd = $mainMod, 9, switch to workspace 9, workspace, 9
bindd = $mainMod, 0, switch to workspace 10, workspace, 10

# ~ Switch workspaces relative to the active workspace with $mainMod + CTRL + [←→] ~ #
bindd = $mainMod_Ctrl, right, Switch to relative workspace → right (forwards), workspace, r+1
bindd = $mainMod_Ctrl, left,  Switch to relative workspace ← left (backwards), workspace, r-1

# ~ move to the first empty workspace instantly with $mainMod + CTRL + [↓] ~ #
bindd = $mainMod_Ctrl, down, Switch to an empty workspace, workspace, empty

# ~ Resize Active window/s ~ #
#           right   =   →
#         up/down   =  ↑ ↓
#            left   =   ←
bindde = $mainMod_Shift, right, Resize active window/s ( → ) by {30px}, resizeactive, 30 0
bindde = $mainMod_Shift, up,    Resize active window/s ( ↑ ) by {30px}, resizeactive, 0 -30
bindde = $mainMod_Shift, left,  Resize active window/s ( ← ) by {30px}, resizeactive, -30 0
bindde = $mainMod_Shift, down,  Resize active window/s ( ↓ ) by {30px}, resizeactive, 0 30

# ~ Move active window to a workspace with $mainMod_Shift + [0-9] ~ #
bindd = $mainMod_Shift, 1, Move acitve window to workspace [1], movetoworkspace, 1
bindd = $mainMod_Shift, 2, Move acitve window to workspace [2], movetoworkspace, 2
bindd = $mainMod_Shift, 3, Move acitve window to workspace [3], movetoworkspace, 3
bindd = $mainMod_Shift, 4, Move acitve window to workspace [4], movetoworkspace, 4
bindd = $mainMod_Shift, 5, Move acitve window to workspace [5], movetoworkspace, 5
bindd = $mainMod_Shift, 6, Move acitve window to workspace [6], movetoworkspace, 6
bindd = $mainMod_Shift, 7, Move acitve window to workspace [7], movetoworkspace, 7
bindd = $mainMod_Shift, 8, Move acitve window to workspace [8], movetoworkspace, 8
bindd = $mainMod_Shift, 9, Move acitve window to workspace [9], movetoworkspace, 9
bindd = $mainMod_Shift, 0, Move acitve window to workspace [10], movetoworkspace, 10

# ~ Move active window to a relative workspace with $mainMod_Alt_Ctrl + [←→] (Left/Right Arrow keys) ~ #
bindd = $mainMod_Alt_Ctrl,right, comment, movetoworkspace, r+1
bindd = $mainMod_Alt_Ctrl, left, comment, movetoworkspace, r-1

# ~ Move active window around current workspace with $mainMod_Ctrl_Shift + [←→↑↓] (Left/Right Up/Down Arrow keys) ~ #
# PS: Note that the $mainMod_Ctrl_Shift + [↑↓] only works if there is 3 or more windows
bindd = $mainMod_Ctrl_Shift, right, Move position of current active window to the right beside a non active window, movewindow, r
bindd = $mainMod_Ctrl_Shift, up,    Move position of current acitve window to the top sides of a non active window, movewindow, u
bindd = $mainMod_Ctrl_Shift, down,  Move position of current acitve window to the down sides of a non active window, movewindow, d
bindd = $mainMod_Ctrl_Shift, left,  Move position of current acitve window to the left beside of a non acitve window, movewindow, l 
