
# ╭──────────────────────╮ #
# │ Volume Knob Bindings │ #
# ╰──────────────────────╯ #

# ~ Switch workspaces with mainMod + [Volumecontrol Knob] ~ #

bindd = $mainMod, XF86AudioRaiseVolume, Quickyly switch to new workspaces → right (forwards), workspace, e+1
bindd = $mainMod, XF86AudioLowerVolume, Quickyly switch to new workspaces ← left (backwards), workspace, e-1

# ~ Move workspaces relative to the active workspace with $mainModCtrl + [Volumecontrol Knob] ~ #

bindd = $mainMod_Ctrl, XF86AudioRaiseVolume, Move to relative workspaces → right (forwards), workspace, r+1
bindd = $mainMod_Ctrl, XF86AudioLowerVolume, Move to relative workspaces ← left (backwards), workspace, r-1

# ~ Move active window to a workspace with $mainModShift + [Volumecontrol Knob] ~ #

bindd = $mainMod_Shift, XF86AudioRaiseVolume, movetoworkspace, +1
bindd = $mainMod_Shift, XF86AudioLowerVolume, movetoworkspace, -1
