
# ╭───────────────────╮ #
# │ APPLICATION BINDS │ #
# ╰───────────────────╯ #

# Variable for AppLauncher
$appLaucher = $sourcePath/rofilaunch.sh

# Variable for switching AppLauncher styles
$appLauncherStyles = $sourcePath/rofiselect.sh

# Variable for WebBrowser
$webBrowser = brave --ozone-platform=wayland --password-store=basic

# Variable for CodeEditor
$codeEditor = code --ozone-platform=wayland

# Variables for Terminal Emulator
$terminalEmulator = kitty
$terminalEmulatorAlt = foot

# Variables for Applications
$musicPlayer = audacious

# ~ Kill an app ~ #
bindd = $mainMod, Q, Kill the current active window except Steam, exec, $sourcePath/dontkillsteam.sh
bindd = $mainMod, Q, Kill the current active window, exec, killactive ""

# ╭───────────────╮ #
# │ Apps Launcher │ #
# ╰───────────────╯ #

bindd = $mainModSpace, Open the AppLauncher, exec, pkill -x rofi || $appLaucher     # Lauch desktop applications

# ╭────────────────╮ #
# │   QUICK APPS   │ #
# ╰────────────────╯ #

bindd = $mainMod, A, Change the AppLauncher style, exec, pkill -x rofi || $appLauncherStyles    # Lauch applauncher style switcher
bindd = $mainMod, B, Launch the default WebBrowser, exec, $Browser      # Lauch your favourite WebBrowser
bindd = $mainMod, C, Launch the CodeEditor, exec, $codeEditor        # Lauch your favourite CodeEditor
bindd = $mainMod, D, Launch the DiscordMessenger, exec, discord --ozone-platform=wayland --enable-wayland-ime --no-sandbox       # Lauch DiscordMessenger
bindd = $mainMod, E, Launch the FileExplorer, exec, $fileExplorer       # Launch your favourite FileExplorer
bindd = $mainMod, M, Launch the MusicPlayer, exec, $musicPlayer         # Launch your favourite Music Player
binds = $mainMod, T, Launch the TerminalEmulatoer, exec, $terminal  # open terminal
