
# ╭───────────────╮ #
# │ Audio Control │ #
# ╰───────────────╯ #

bindl  = , XF86AudioPlay, exec, playerctl play-pause
bindl  = , XF86AudioPause, exec, playerctl play-pause
bindl  = , XF86AudioNext, exec, playerctl next
bindl  = , XF86AudioPrev, exec, playerctl previous
bindl  = , XF86AudioMicMute, exec, $scrPath/volumecontrol.sh -i m # toggle microphone mute
bindl = , Xf86AudioMute, exec, $scrPath/volumecontrol.sh -o m # toggle audio mute
bindel = , XF86AudioLowerVolume, exec, $scrPath/volumecontrol.sh -o d # decrease volume
bindel = , XF86AudioRaiseVolume, exec, $scrPath/volumecontrol.sh -o i # increase volume
  # bindl  = , F10, exec, $scrPath/volumecontrol.sh -o m # toggle audio mute
  # bindel = , F11, exec, $scrPath/volumecontrol.sh -o d # decrease volume
  # bindel = , F12, exec, $scrPath/volumecontrol.sh -o i # increase volume
