
# ╭────────────────────╮ #
# │ Brightness Control │ #
# ╰────────────────────╯ #

# Brightness control
bindel = $mainMod, F4, exec, $scrPath/brightnesscontrol.sh i # increase brightness
bindel = $mainMod, F3, exec, $scrPath/brightnesscontrol.sh d # decrease brightness
bindel = , XF86MonBrightnessUp, exec, $scrPath/brightnesscontrol.sh i # increase brightness
bindel = , XF86MonBrightnessDown, exec, $scrPath/brightnesscontrol.sh d # decrease brightness
