
# ╭──────────────────╮ #
# │ GLOBAL VARIABLES │ #
# ╰──────────────────╯ #

# Variable for SOURCE PATH 
$sourcePath = $HOME/.local/share/bin

# Variable for LOCK SCREEN
$lockScreen = swaylock

# Variables for ClipBoard ( Text, Image )
$clipboardTexts = wl-paste --type text --watch cliphist store       # Store ClipBoard Data type ( Text )
$clipboardImages = wl-paste --type image --watch cliphist store     # Store ClipBoard Data type ( Image )

