
# +          ----*----          + #
# + ╔═════════════════════════╗ + #
# + ║ HYPRLAND CONFIGURATIONS ║ + #
# + ╚═════════════════════════╝ + #
# +          ----*----          + #

# + ~ COMMENT THE FOLLOWING LINE BELOW TO DISABLE AUTOSTART OF CODE ~ #
exec-once = code ~/.config/hypr/hyprland.conf    # COMMENT TO DISABLE #

# ╭───────────────╮ #
# │ Main Modifier │ #
# ╰───────────────╯ #

# + ~ The Main variable defualt modifier is `SUPER` aka `WINDOWS/CMD` key. ~ + #
# # ~ Can be modified to `CTRL` or `ALT` or `SHIFT` or `CAPSLOCK`. ~ # #
$mainMod = SUPER

# + ~ Uncomment the following line below to use `CAPSLOCK` as the Main variable modifier ~ + #
# $mainMod = CAPSLOCK

# # + ~ Combined Main variable modifier: $mainMod + ALT + # #
$mainMod_Alt = $mainMod ALT

# # + Combined Main variable modifier: $mainMod + CTRL + # #
$mainMod_Ctrl = $mainMod CTRL

# # + Combined Main variable modifier: $mainMod + SHIFT + # #
$mainMod_Shift = $mainMod SHIFT

# # + Other Combined Main variable modifier: $mainMod + ALT + SHIFT + # #
$mainMod_Alt_Shift = $mainMod ALT+SHIFT

# # + Other Combined Main variable modifier: $mainMod + CTRL + SHIFT + # #
$mainMod_Ctrl_Shift = $mainMod CTRL+SHIFT

# # + Other Combined Main variable modifier: $mainMod + ALT + CTRL + # #
$mainMod_Alt_Ctrl = $mainMod Alt ALT+CTRL

# # + Other Combined Main variable modifier: $mainMod + ALT + CTRL + SHIFT + # #
$mainMod_Alt_Ctrl_Shift = $mainMod+Alt CTRL+SHIFT

$ctrl_Shift_Escape = CTRL+SHIFT, ESCAPE

# ╭──────────────────────╮ #
# │ Miscellaneous Config │ #
# ╰──────────────────────╯ #

# See https://wiki.hyprland.org/Configuring/Variables/

misc {
    
    # ~ Monitor stuff ~ #
    vrr = 0
    
    # ~ Wallpaper stuff ~ #
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    
    # Animation stuff
    animate_manual_resizes = true
    animate_mouse_window_dragging = true
    
    # ~ QOL stuff ~ #
    # middle_click_paste = false
}

xwayland {
    
    # ~ Scaling stuff ~ #
    force_zero_scaling = true
    
}

# Load cursors
exec = hyprctl setcursor Bibata-Modern-Ice 20
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec = gsettings set org.gnome.desktop.interface cursor-size 20

# ╭───────────────╮ #
# │ Source Config │ #
# ╰───────────────╯ #

# ~ Source Animation Configurations ~ #
source = ~/.config/hypr/animations.conf

# ~ Source Application Bindings Configurations ~ #
source = ~/.config/hypr/application_binds.conf

# ~ Source Auto Start Services Configurations ~ #
source = ~/.config/hypr/auto_start.conf

# ~ Source Device Configurations ~ #
source = ~/.config/hypr/devices.conf

# ~ Source Environment Variables Configurations ~ #
source = ~/.config/hypr/env_vars.conf

# ~ Source Global Variables Configurations ~ #
source = ~/.config/hypr/global_vars.conf

# ~ Source Key Bindings Configurations ~ #
source = ~/.config/hypr/keybindings.conf

# ~ Source Layer Rules Configurations ~ #
source = ~/.config/hypr/layer_rules.conf

# ~ Source Layout Configurations ~ #
source = ~/.config/hypr/layouts.conf

# ~ Monitors Configurations ~ #
source = ~/.config/hypr/monitors.conf

# ~ Source Window Rules Configurations ~ #
source = ~/.config/hypr/window_rules.conf
