
# ╭─────────────╮ #
# │ Layer Rules │ #
# ╰─────────────╯ #

# Blur rofi
layerrule = blur, rofi
layerrule = ignorezero, rofi

# Blur waybar
layerrule = blur,waybar

# Blur notifications
layerrule = blur, notifications
layerrule = ignorezero, notifications

# blur logout menu
layerrule = blur, logout_dialog

# Blur SwayNC
# layerrule = blur,swaync-notification-window
# layerrule = ignorezero,swaync-notification-window
# layerrule = blur,swaync-control-center
# layerrule = ignorezero,sway~nc-control-center
