
# ╭────────────────╮ #
# │ Mouse Bindings │ #
# ╰────────────────╯ #

# ~ Scroll through existing workspaces with mainMod + scroll ~ #
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# ~ Move/Resize windows with mainMod + LMB/RMB and dragging ~ #
binddm = $mainMod, mouse:272, Move window/s around with Left Mouse Button, movewindow
binddm = $mainMod, mouse:273, Resize windows around with Right Mouse Button ,resizewindow
binddm = Super, Z, Move window/s around, movewindow
binddm = Super, X, Resize windows around, resizewindow
